<?php
/**
 * SpecGroupType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetGenerator
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Generator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetGenerator\Model;
use \Aurigma\AssetGenerator\ObjectSerializer;

/**
 * SpecGroupType Class Doc Comment
 *
 * @category Class
 * @description Specification group type.
 * @package  Aurigma\AssetGenerator
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpecGroupType
{
    /**
     * Possible values of this enum
     */
    public const PACKAGING = 'Packaging';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PACKAGING
        ];
    }
}


